spring:
  jpa:
    #    show-sql: true
    hibernate:
      ddl-auto: validate
  #    properties:
  #      hibernate:
  #        format_sql: true
  liquibase:
    enabled: ${LIQUIBASE_ENABLED:true}
    change-log: classpath:/db/db.changelog-master.yaml
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://postgres:5432/social_media_db}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
server:
  port: 8000
logging:
  level:
    org.springframework: INFO
    # Enable hibernate sql log
    org.hibernate.SQL: DEBUG
    # Log sql parameters. For Hibernate 5 version
    org.hibernate.type.descriptor.sql: TRACE
    # Log sql parameters. For Hibernate 6 version
#    org.hibernate.orm.jdbc.bind: TRACE