spring:
  datasource:
# To use Testcontainers we first need to modify the protocol part of the JDBC URL.
# We add tc: after the jdbc:, followed by the container we want to use in our test.
# Because the host and port are unimportant for Testcontainers, we can skip them by using a host-less URI (///).
    url: jdbc:tc:postgresql:latest:///spring_boot_testcontainers
  test:
    database:
# @DataJpaTest would still try to use an H2 database. By adding this property we turn this behavior off again.
      replace: none