routes:
  uri:
    order-service: http://localhost:8050

spring:
  security:
    oauth2:
      client:
        provider:
          # The provider name can be a custom value, but you need to use this exact name while using it
          # in the client registration properties.
          my_provider:
            issuer-uri: http://localhost:8080/auth/realms/flowing-realm
        registration:
          # The client registration name can be any custom name.
          # It is used to just identify the client in your application
          my_keycloak:
            provider: my_provider
            client-id: flowing-client
            client-secret: 0gVRj8TBqRdcZK6M9NBK4De37ssJBz1l
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/gateway"
            scope: openid, message.read
