routes:
  uri:
    product-service: http://product-service:8000

spring:
  security:
    oauth2:
      client:
        provider:
          my_provider:
            issuer-uri: http://keycloak:8080/auth/realms/flowing-realm
        registration:
          my_keycloak:
            provider: my_provider
            client-id: auth-client
            client-secret: 0gVRj8TBqRdcZK6M9NBK4De37ssJBz1l
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/gateway"
            scope: openid, message.read
